
###
 POST   http://localhost:8000/register
Content-Type: application/json

{

  
  "full_name": "elijah Kimani ",
  "email": "elijahkimani1293@gmail.com",
  "contact_phone": "0791337188",
  "address": "123 kenya",
  "role": "user",
  "password": "40284433"
  
}

###

POST    http://localhost:8000/login
Content-Type: application/json

  {  
    "email": "elijahkimani1293@gmail.com",
    "password": "40284433"
  }
