
###
 POST   http://localhost:8000/register
Content-Type: application/json

{

  
  "full_name": "johnnn ",
  "email": "johnndoen@examples.com",
  "contact_phone": "07943995956",
  "address": "123 Oahkk St",
  "role": "user",
  "password": "newseeccurepasswordd"
}

###

POST    http://localhost:8000/login
Content-Type: application/json

  {  
    "email": "johndoe@examples.com",
    "password": "newsecurepasswordd"
    
  }
