#  GETTING ALL CustomerSupportTickets----------------------------------------------------------------
###

GET http://localhost:8000/customersupport

# Getting CustomerSupportTickets by ID
###
GET http://localhost:8000/customersupport/9

###
#Deleting CustomerSupportTickets by ID
DELETE http://localhost:8000/customersupport/1

###

POST  http://localhost:8000/customersupport
Content-Type: application/json


 {

    
  }


###
PUT http://localhost:8000/customersupport/9
Content-Type: application/json

{

    "user_id": 42,
    "subject": "ghhsdgd",
    "description": "trt",
    "status": "kimkim"
}
    

