#  GETTING ALL USERS----------------------------------------------------------------
###

GET http://localhost:8000/users

# Getting user by ID
###
GET http://localhost:8000/users/9

###
#Deleting user by ID
DELETE http://localhost:8000/users/1

###

POST  http://localhost:8000/users
Content-Type: application/json

 {

    
  }


###
PUT http://localhost:8000/users/1
Content-Type: application/json

{

  
}
    

