#  GETTING ALL USERS----------------------------------------------------------------
###

GET http://localhost:8000/vehicles

# Getting user by ID
###
GET http://localhost:8000/vehicles/5

###
#Deleting user by ID
DELETE http://localhost:8000/vehicles/3

###

POST  http://localhost:8000/vehicles
Content-Type: application/json

 {

    
  }


###
PUT http://localhost:8000/vehicles/5
Content-Type: application/json

 {
    "id": 5,
    "vehicleSpec_id": 1,
    "rental_rate": "4000.00",
    "availability": true
  
  }

