#  GETTING ALL FLEETMANAGEMENT----------------------------------------------------------------
###

GET http://localhost:8000/FleetManagement

# Getting FLEETMANAGEMENT by ID
###
GET http://localhost:8000/FleetManagement/9

###
#Deleting FLEETMANAGEMENT by ID
DELETE http://localhost:8000/FleetManagement/1

###

POST  http://localhost:8000/FleetManagement
Content-Type: application/json

 {
    "id": 4,
    "vehicle_id": 5,
    "acquisition_date": 6000,
    "depreciation_rate": 24455,
    "current_value": 4000,
    "maintenance_cost": 300,
    "status": pending
    
  }
]


###
PUT http://localhost:8000/fleetmanagement/1
Content-Type: application/json

{

  
}
    

