#  GETTING ALL Vehicles----------------------------------------------------------------
###

GET http://localhost:8000/users

# Getting Vehicles by ID
###
GET http://localhost:8000/users/5

###
#Deleting Vehicles by ID
DELETE http://localhost:8000/users/3

###

POST  http://localhost:8000/users
Content-Type: application/json

  

###
PUT http://localhost:8000/users/7
Content-Type: application/json

  {
  
    
  } 
