#  GETTING ALL Payments----------------------------------------------------------------
###

GET http://localhost:8000/payments

# Getting user by ID
###
GET http://localhost:8000/payments/9

###
#Deleting user by ID
DELETE http://localhost:8000/payments/1

###

POST  http://localhost:8000/checkout-session
Content-Type: application/json

 {
   "booking_id" : 1,
   "user_id":"3",
   "total_amount" :455
  
  }


###
PUT http://localhost:8000/payments/1
Content-Type: application/json

{

  
}

 